<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DomicilioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         $calles = [
            "Avenida de los Insurgentes",
            "Paseo de la Reforma",
            "Avenida Chapultepec",
            "Calle 5 de Febrero",
            "Calle 16 de Septiembre",
            "Avenida Juárez",
            "Calle Madero",
            "Calle Hidalgo",
            "Avenida Revolución",
            "Calle de la Paz",
            "Calle de la Libertad",
            "Avenida del Trabajo",
            "Calle de la Amistad",
            "Calle de los Héroes",
            "Avenida del Sol",
            "Calle del Río",
            "Calle de las Flores",
            "Avenida de la Constitución",
            "Calle del Carmen",
            "Avenida de la Independencia",
            "Calle de la Cultura",
            "Calle del Progreso",
            "Avenida de los Abetos",
            "Calle de la Alegría",
            "Calle de los Maestros",
            "Avenida de la Familia",
            "Calle de la Esperanza",
            "Calle de la Historia",
            "Calle de los Ángeles",
            "Avenida de la Paz",
            "Calle de la Fraternidad",
            "Calle de la Innovación",
            "Calle de la Creatividad",
            "Avenida de los Valores",
            "Calle de la Naturaleza",
            "Calle de la Ecología",
            "Calle de la Salud",
            "Avenida de la Cultura",
            "Calle de la Memoria",
            "Calle de la Tradición",
            "Calle de la Unidad",
            "Avenida de la Juventud",
            "Calle de la Solidaridad",
            "Calle de la Diversidad",
            "Calle de la Inclusión",
            "Calle de la Igualdad",
            "Calle de la Responsabilidad",
            "Calle de la Honestidad",
            "Avenida de la Transparencia",
            "Calle de la Lealtad",
            "Calle de la Verdad",
            "Calle de la Compasión",
            "Calle de la Generosidad",
            "Calle de la Bondad",
            "Avenida de la Empatía",
            "Calle de la Sabiduría",
            "Calle de la Comprensión",
            "Calle de la Amistad",
            "Calle de la Esperanza",
            "Calle de la Creatividad",
            "Avenida de los Derechos Humanos",
            "Calle de la Innovación",
            "Calle de la Tolerancia",
            "Avenida del Futuro",
            "Calle de la Amistad Internacional",
            "Calle de la Paz Mundial",
            "Calle de la Ciencia",
            "Calle de la Tecnología",
            "Calle de la Educación",
            "Avenida de la Democracia",
            "Calle de la Justicia",
            "Calle de la Libertad de Expresión",
            "Calle de la Solidaridad Social",
            "Calle de la Diversidad Cultural",
            "Avenida de la Inclusión",
            "Calle de la Igualdad de Oportunidades",
            "Calle de la Responsabilidad Ciudadana",
            "Calle de la Honestidad Profesional",
            "Avenida de la Transparencia Gubernamental",
            "Calle de la Lealtad Familiar",
            "Calle de la Verdad Histórica",
            "Calle de la Compasión Comunitaria",
            "Calle de la Generosidad Social",
            "Calle de la Bondad Personal",
            "Avenida de la Empatía Global",
            "Calle de la Sabiduría Ancestral",
            "Calle de la Comprensión Intercultural",
            "Calle de la Amistad Duradera",
            "Calle de la Esperanza Colectiva",
            "Calle de la Creatividad Artística",
            "Avenida de los Derechos Civiles",
            "Calle de la Innovación Empresarial",
            "Calle de la Tolerancia Religiosa",
            "Avenida del Desarrollo Sostenible",
            "Calle de la Educación Inclusiva",
            "Calle de la Justicia Social",
            "Calle de la Libertad Creativa",
            "Calle de la Solidaridad Internacional",
            "Calle de la Diversidad Étnica",
            "Avenida de la Inclusión Social"
        ];

        $colonias = [
            "Roma",
            "Condesa",
            "Polanco",
            "Del Valle",
            "Santa Fe",
            "Narvarte",
            "Lomas de Chapultepec",
            "San Ángel",
            "Coyoacán",
            "Tlalpan",
            "Cuauhtémoc",
            "Miguel Hidalgo",
            "Escandon",
            "Santa María la Ribera",
            "Jardines del Pedregal",
            "San Jerónimo",
            "Chimalistac",
            "Tacubaya",
            "San Rafael",
            "Nápoles",
            "Roma Sur",
            "San Miguel Chapultepec",
            "La Merced",
            "Guerrero",
            "Morelos",
            "Tepito",
            "Santa Cruz Atoyac",
            "San Agustín",
            "Mixcoac",
            "Villa de Cortés",
            "La Villa",
            "San Pedro de los Pinos",
            "San Juan de Aragón",
            "Iztacalco",
            "Azcapotzalco",
            "Xochimilco",
            "La Magdalena Contreras",
            "Tláhuac",
            "Álvaro Obregón",
            "Benito Juárez",
            "Coyoacán",
            "Cuajimalpa",
            "Milpa Alta",
            "Venustiano Carranza",
            "Tlalnepantla",
            "Ecatepec",
            "Nezahualcóyotl",
            "Naucalpan",
            "Huixquilucan",
            "Atizapán",
            "Cuautitlán",
            "Tultitlán",
            "Chalco",
            "Ixtapaluca",
            "Texcoco",
            "Chimalhuacán",
            "La Paz",
            "San Vicente Chicoloapan",
            "Coacalco",
            "San Martín Texmelucan",
            "Ecatepec de Morelos",
            "Xonacatlán",
            "Valle de Chalco",
            "Santa María Chiconautla",
            "San Felipe del Progreso",
            "Tepotzotlán",
            "Jilotepec",
            "Tepalcatepec",
            "Tlalmanalco",
            "Amecameca",
            "Cuautitlán Izcalli",
            "San Juan Ixhuatepec",
            "San Lorenzo Almecatla",
            "San Francisco Tlaltenco",
            "San José del Rincón",
            "Chiconcuac",
            "San Nicolás",
            "San Bartolo",
            "Santa Teresa",
            "San Juan de Aragón",
            "San Sebastián",
            "San Mateo",
            "San Cristóbal",
            "San Miguel Teotongo",
            "San Andrés",
            "San Felipe",
            "San Lucas",
            "San Pedro",
            "San Juan",
            "San Pablo",
            "San Miguel",
            "San José",
            "San Agustín",
            "San Antonio",
            "San Vicente",
            "San Bartolo",
            "San Ramón",
            "San Salvador",
            "San Juanico",
            "San Juan de Dios",
            "San Juan de la Vega",
            "San Juan de la Barrera",
            "San Juan de la Cruz",
            "San Juan de la Paz",
            "San Juan de los Morros",
            "San Juan de los Reyes",
            "San Juan de los Siete",
            "San Juan de los Ángeles",
            "San Juan de los Santos",
            "San Juan de los Vientos"
        ];

        $municipios = [
            "Álvaro Obregón",
            "Amozoc",
            "Apizaco",
            "Atizapán de Zaragoza",
            "Bacalar",
            "Bahía de Banderas",
            "Cabo San Lucas",
            "Campeche",
            "Cancún",
            "Chilpancingo",
            "Chihuahua",
            "Coatzacoalcos",
            "Colima",
            "Cuernavaca",
            "Culiacán",
            "Durango",
            "Ecatepec",
            "Ensenada",
            "Guanajuato",
            "Guadalajara",
            "Hermosillo",
            "Irapuato",
            "La Paz",
            "León",
            "Mazatlán",
            "Mérida",
            "Mexicali",
            "Monterrey",
            "Morelia",
            "Tijuana",
            "Toluca",
            "Torreón",
            "Veracruz",
            "Villahermosa",
            "Zacatecas",
            "Acapulco",
            "Aguascalientes",
            "Benito Juárez",
            "Boca del Río",
            "Chalco",
            "Chihuahua",
            "Cozumel",
            "Cuautitlán Izcalli",
            "Ecatepec de Morelos",
            "González",
            "Guadalupe",
            "Ixtapaluca",
            "Juárez",
            "La Magdalena Contreras",
            "Lázaro Cárdenas",
            "Metepec",
            "Naucalpan",
            "Nezahualcóyotl",
            "Oaxaca de Juárez",
            "Pachuca",
            "Puebla",
            "Querétaro",
            "Reynosa",
            "San Cristóbal de las Casas",
            "San Luis Potosí",
            "San Nicolás",
            "Santa Catarina",
            "Santiago de Querétaro",
            "Tlalnepantla",
            "Tlaxcala",
            "Tultitlán",
            "Veracruz",
            "Xalapa",
            "Zacatlán",
            "Zamora",
            "Zihuatanejo",
            "Zumpango",
            "Cihuatlán",
            "Coyoacán",
            "Tlalpan",
            "Chimalhuacán",
            "San Juan de los Morros",
            "San Juan del Río",
            "San Fernando",
            "Torreón",
            "Zacatecas",
            "Matamoros",
            "Piedras Negras",
            "San Andrés Cholula",
            "San Felipe del Progreso",
            "San José del Cabo",
            "San Luis Río Colorado",
            "San Martín Texmelucan",
            "San Miguel de Allende",
            "San Salvador",
            "San Vicente Chicoloapan",
            "Tampico",
            "Tlaxcala",
            "Torreón",
            "Valle de Bravo",
            "Zacatecas"
        ];

        $estados = [
            "Aguascalientes",
            "Baja California",
            "Baja California Sur",
            "Campeche",
            "Chiapas",
            "Chihuahua",
            "Coahuila",
            "Colima",
            "Durango",
            "Guanajuato",
            "Guerrero",
            "Hidalgo",
            "Jalisco",
            "Mexico",
            "Michoacán",
            "Morelos",
            "Nayarit",
            "Nuevo León",
            "Oaxaca",
            "Puebla",
            "Querétaro",
            "Quintana Roo",
            "San Luis Potosí",
            "Sinaloa",
            "Sonora",
            "Tabasco",
            "Tamaulipas",
            "Tlaxcala",
            "Veracruz",
            "Yucatán",
            "Zacatecas"
        ];

        
        $codigos_postales = [
            "01000", "01010", "01020", "01030", "01040",
            "01050", "01060", "01070", "01080", "01090",
            "01100", "01110", "01120", "01130", "01140",
            "01150", "01160", "01170", "01180", "01190",
            "01200", "01210", "01220", "01230", "01240",
            "01250", "01260", "01270", "01280", "01290",
            "01300", "01310", "01320", "01330", "01340",
            "01350", "01360", "01370", "01380", "01390",
            "01400", "01410", "01420", "01430", "01440",
            "01450", "01460", "01470", "01480", "01490",
            "01500", "01510", "01520", "01530", "01540",
            "01550", "01560", "01570", "01580", "01590",
            "01600", "01610", "01620", "01630", "01640",
            "01650", "01660", "01670", "01680", "01690",
            "01700", "01710", "01720", "01730", "01740",
            "01750", "01760", "01770", "01780", "01790",
            "01800", "01810", "01820", "01830", "01840",
            "01850", "01860", "01870", "01880", "01890",
            "01900", "01910", "01920", "01930", "01940",
            "01950", "01960", "01970", "01980", "01990",
            "02000", "02010", "02020", "02030", "02040"
        ];

        $domiciliosEstudiantes = [];
        $domiciliosAdmins = [];

        for ($i = 1; $i < 723; $i++) {
            $domiciliosEstudiantes[] = [
               "calle" => $calles[array_rand($calles)],
               "numero_exterior" => rand(1, 100),
               "numero_interior" => rand(1, 100),   
               "colonia" => $colonias[array_rand($colonias)],
               "municipio" => $municipios[array_rand($municipios)],
               "estado" => $estados[array_rand($estados)],
               "codigo_postal" => $codigos_postales[array_rand($codigos_postales)],
               "pais" => "México",
               "created_at" => Carbon::now(),
               "updated_at" => Carbon::now(),
            ];
        }

        for ($i = 723; $i < 729; $i++) {
            $domiciliosAdmins[] = [
               "calle" => $calles[array_rand($calles)],
               "numero_exterior" => rand(1, 100),
               "numero_interior" => rand(1, 100),   
               "colonia" => $colonias[array_rand($colonias)],
               "municipio" => $municipios[array_rand($municipios)],
               "estado" => $estados[array_rand($estados)],
               "codigo_postal" => $codigos_postales[array_rand($codigos_postales)],
               "pais" => "México",
               "created_at" => Carbon::now(),
               "updated_at" => Carbon::now(),
            ];
        }


        DB::table('domicilios')->insert($domiciliosEstudiantes);
        DB::table('domicilios')->insert($domiciliosAdmins);
    }
}
